name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.408'
    - name: Restore dependencies
      run: |
        dotnet restore \ProjectHive.Services.AuthAPI\ProjectHive.Services.AuthAPI.csproj
        dotnet restore \ProjectHive.Services.ProjectsAPI\ProjectHive.Services.ProjectsAPI.csproj
        dotnet restore \ProjectHive.Services.NotificationsAPI\ProjectHive.Services.NotificationsAPI.csproj
        dotnet restore \ProjectHive.Services.ReportsAPI\ProjectHive.Services.ReportsAPI.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
