name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: |
        dotnet restore ProjectHive/ProjectHive.Services.AuthAPI/ProjectHive.Services.AuthAPI.csproj
        dotnet restore ProjectHive/ProjectHive.Services.ProjectsAPI/ProjectHive.Services.ProjectsAPI.csproj
        dotnet restore ProjectHive/ProjectHive.Services.NotificationsAPI/ProjectHive.Services.NotificationsAPI.csproj
        dotnet restore ProjectHive/ProjectHive.Services.ReportsAPI/ProjectHive.Services.ReportsAPI.csproj
        dotnet restore ProjectHive/ProjectHive.Services.Core/ProjectHive.Services.Core.csproj
        dotnet restore ProjectHive/ProjectHive.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
